services:
  - type: web
    name: seatreservation
    runtime: docker
    plan: free
    autoDeploy: false
    healthCheckPath: /actuator/health/readiness
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: DB_HOST
        fromDatabase:
          name: booking-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: booking-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: booking-db
          property: name
      - key: DATABASE_USERNAME
        fromDatabase:
          name: booking-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: booking-db
          property: password

databases:
  - name: booking-db
    plan: free
    databaseName: booking
    user: booking
